apiVersion: configs.skyu.io/v1
kind: SkyUConfig
metadata:
  name: check-ridmi
  namespace: hello-dev
  labels:
    organizationId: org_3ead97cf-c1ec-4b6a-a30e-3a81e9bbbd1a
    projectId: project_70ec9eb3-3553-427c-8634-67e73ba58cd7
    environmentId: env_c6e2d6a6-5ffb-49fe-9525-9f5ef9367800
spec:
  data:
    db_url: ${{secret::secret_a89f51d7-b171-435c-ba3e-5986137fabc2:}}
  skyuControlPlaneAPI:
    organizationId: org_3ead97cf-c1ec-4b6a-a30e-3a81e9bbbd1a
    projectId: project_70ec9eb3-3553-427c-8634-67e73ba58cd7
