apiVersion: configs.skyu.io/v1
kind: SkyUConfig
metadata:
  name: ridmi-config-new
  namespace: hello-dev
  labels:
    organizationId: org_3ead97cf-c1ec-4b6a-a30e-3a81e9bbbd1a
    projectId: project_70ec9eb3-3553-427c-8634-67e73ba58cd7
    environmentId: env_c6e2d6a6-5ffb-49fe-9525-9f5ef9367800
spec:
  data:
    fileContent-0qcolr: "{\r\n    \"db\":\"${{secret::secret_43a84ea1-b1d2-48fc-8782-e584f3929d88:}}\",\r\n    \"db_url\":\"${{secret::secret_4b480904-ff7a-42ae-af41-c1c5f6548dde:}}\"\r\n}"
  skyuControlPlaneAPI:
    organizationId: org_3ead97cf-c1ec-4b6a-a30e-3a81e9bbbd1a
    projectId: project_70ec9eb3-3553-427c-8634-67e73ba58cd7
